<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Add Customer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
  <?php require("assets/bootstrap.min.css"); ?>
  <?php require("assets/styles.css"); ?>
</style>
<body>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-12 col-sm-6 col-md-6 mt16' >
        <h1 class='mt48 mb24'> Create New Customer</h1>

        <div class='row'>
          <div class='col-sm-12 mt24'>
            <div class='alert ' id='alertDiv' role="alert" style='display:none'>
              <button type="button" class="close" id='alertCloseBtn' data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <p id='alertContent'></p>
            </div>
          </div>
          
        </div>

        <form method='post' action='/public/customers/create'>
          <div class='form-group'>
            <label for='firstNameInput'>First Name</label>
            <input type='text' class='form-control' name='first_name' id='firstNameInput' placeholder='John'/>
          </div>
          <div class='form-group'>
            <label for='lastNameInput'>Last Name</label>
            <input type='text' class='form-control' name='last_name' id='lastNameInput' placeholder='Doe'/>
          </div>
          <div class='form-group'>
            <label for='emailInput'> Email</label>
            <input type='email' class='form-control' name='email' id='emailInput' placeholder='name@example.com' />
          </div>
          <div class='form-group'>
            <label for='phoneInput'>Phone</label>
            <input type='text' class='form-control' name='phone' id='phoneInput' placeholder='555-123-4567-77'/>
          </div>
          <div class='form-group'>
            <button class='btn btn-primary' type='submit' name='addBtn' id='addBtnPhp'>Submit(PHP)</button>
            <button class='btn btn-primary' id='addBtnJs' >Submit(JS)</button>
            <button class='btn btn-secondary' name='cancelBtn' id='formCancelBtn'> Cancel</button>    
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

<script type='text/javascript'>

  document.getElementById('formCancelBtn').addEventListener('click', function(e){
    e.preventDefault();
    window.location.replace("http://localhost:8080/public/customers");
  });

  document.getElementById('addBtnJs').addEventListener('click', function(e){
    e.preventDefault();
  
    var custFirstNameVal = document.getElementById("firstNameInput").value;
    var custLastNameVal = document.getElementById("lastNameInput").value;
    var custEmailVal = document.getElementById("emailInput").value;
    var custPhoneVal = document.getElementById("phoneInput").value;

    if (!custFirstNameVal || !custLastNameVal || !custEmailVal || !custPhoneVal){
      document.getElementById('alertDiv').style.display = "block";
      document.getElementById('alertDiv').classList.add('alert-danger');
      document.getElementById('alertContent').innerHTML = `Please fill values correctly`;
      return;
    }

    var APIURL = `/public/api/customers`;  

    var xhr = new XMLHttpRequest();
    xhr.open('POST', APIURL, true);

    xhr.setRequestHeader('Content-type','application/json; charset=utf-8');

    xhr.onload = function(){
      document.getElementById('alertDiv').style.display = "block";
      document.getElementById('alertDiv').classList.add('alert-success');
      document.getElementById('alertContent').innerHTML = `Customer Created Successfully`;
      
      document.getElementById('alertCloseBtn').addEventListener('click', function(){
        window.location.replace("http://localhost:8080/public/customers");
      });
      
    }

    var customerObject = {
      first_name: custFirstNameVal, 
      last_name: custLastNameVal, 
      email: custEmailVal, 
      phone: custPhoneVal
    }

    var data = JSON.stringify(customerObject);

    xhr.send(data);
  });

</script>

</html>