<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SLIM</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
  <?php require("assets/bootstrap.min.css"); ?>
</style>
<body>
  <div class='container'>
    <h1> Slim PHP App</h1>
    <p> Hey: <strong> <?php echo $theName; ?> </strong></p>
  </div>
</body>
</html>